[package]
name = "random-number-lcm"
version = "0.1.0"
authors = ["mojila <mojila@gitlab.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
